### ISSUE TITLE
Fix Swift 6 strict concurrency compilation errors in macOS app

### ISSUE THREAD

**Issue by pioneerAlone** [pioneerAlone/dsh-notch#8]
## Swift 6 Strict Concurrency Compilation Errors

The macOS native app (`macos/`) fails to compile with Swift 6.0 due to strict concurrency checking. These errors exist in the original codebase before any modifications.

### Errors

**1. `main.swift:5` - `@main` attribute conflict**
```
error: 'main' attribute cannot be used in a module that contains top-level code
```
The file has both `@main` enum and top-level `import` statements.

**2. `RootView.swift:646,648` - Sendable closure accessing @MainActor properties**
```
error: main actor-isolated property 'expanded' can not be referenced from a Sendable closure
error: main actor-isolated property 'model' can not be referenced from a Sendable closure
error: main actor-isolated property 'measuredContentHeight' can not be mutated from a Sendable closure
```
The `.onPreferenceChange` closure is `Sendable` but accesses `@MainActor`-isolated properties.

**3. `StatusOrbit.swift:219,258` - ambiguous `cos` function**
```
error: ambiguous use of 'cos'
```
Swift 6 has both `CoreGraphics.cos(CGFloat)` and `_math.cos(Double)`, causing ambiguity.

### Impact
- The native Notch app cannot be built with Swift 6
- Blocks the Unix socket client integration (which compiles fine)

### Suggested Fixes
1. **main.swift**: Remove `@main` attribute or move imports inside the enum
2. **RootView.swift**: Wrap closure body in `Task { @MainActor in ... }` or use `@MainActor` annotation
3. **StatusOrbit.swift**: Explicitly cast to `CGFloat` or `Double` to disambiguate

### Environment
- Swift 6.0 (swift-tools-version: 6.0)
- macOS 14+
- Xcode Command Line Tools

**Comment by pioneerAlone** [comment]
Fixed Swift 6 strict concurrency compilation errors:

1. **main.swift**: Added @MainActor to DshNotchMain enum and moved main() call to top-level
2. **RootView.swift**: Wrapped onPreferenceChange closure body in Task { @MainActor in ... }
3. **StatusOrbit.swift**: Added explicit CGFloat() conversions for cos/sin results

Build now succeeds with Swift 6.0.
